// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/pkg/proto/colibri (interfaces: ColibriClient,ColibriServer)

// Package mock_colibri is a generated GoMock package.
package mock_colibri

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	colibri "github.com/scionproto/scion/go/pkg/proto/colibri"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockColibriClient is a mock of ColibriClient interface
type MockColibriClient struct {
	ctrl     *gomock.Controller
	recorder *MockColibriClientMockRecorder
}

// MockColibriClientMockRecorder is the mock recorder for MockColibriClient
type MockColibriClientMockRecorder struct {
	mock *MockColibriClient
}

// NewMockColibriClient creates a new mock instance
func NewMockColibriClient(ctrl *gomock.Controller) *MockColibriClient {
	mock := &MockColibriClient{ctrl: ctrl}
	mock.recorder = &MockColibriClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockColibriClient) EXPECT() *MockColibriClientMockRecorder {
	return m.recorder
}

// TestPeer mocks base method
func (m *MockColibriClient) TestPeer(arg0 context.Context, arg1 *colibri.TestingMessage, arg2 ...grpc.CallOption) (*colibri.TestingMessage, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TestPeer", varargs...)
	ret0, _ := ret[0].(*colibri.TestingMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestPeer indicates an expected call of TestPeer
func (mr *MockColibriClientMockRecorder) TestPeer(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestPeer", reflect.TypeOf((*MockColibriClient)(nil).TestPeer), varargs...)
}

// MockColibriServer is a mock of ColibriServer interface
type MockColibriServer struct {
	ctrl     *gomock.Controller
	recorder *MockColibriServerMockRecorder
}

// MockColibriServerMockRecorder is the mock recorder for MockColibriServer
type MockColibriServerMockRecorder struct {
	mock *MockColibriServer
}

// NewMockColibriServer creates a new mock instance
func NewMockColibriServer(ctrl *gomock.Controller) *MockColibriServer {
	mock := &MockColibriServer{ctrl: ctrl}
	mock.recorder = &MockColibriServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockColibriServer) EXPECT() *MockColibriServerMockRecorder {
	return m.recorder
}

// TestPeer mocks base method
func (m *MockColibriServer) TestPeer(arg0 context.Context, arg1 *colibri.TestingMessage) (*colibri.TestingMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestPeer", arg0, arg1)
	ret0, _ := ret[0].(*colibri.TestingMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestPeer indicates an expected call of TestPeer
func (mr *MockColibriServerMockRecorder) TestPeer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestPeer", reflect.TypeOf((*MockColibriServer)(nil).TestPeer), arg0, arg1)
}
