// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.10
// source: proto/control_plane/v1/aliases.proto

package control_plane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAliasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string     `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Replicas []*Replica `protobuf:"bytes,3,rep,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *RegisterAliasRequest) Reset() {
	*x = RegisterAliasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAliasRequest) ProtoMessage() {}

func (x *RegisterAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAliasRequest.ProtoReflect.Descriptor instead.
func (*RegisterAliasRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_aliases_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAliasRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterAliasRequest) GetReplicas() []*Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type RegisterAliasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterAliasResponse) Reset() {
	*x = RegisterAliasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAliasResponse) ProtoMessage() {}

func (x *RegisterAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAliasResponse.ProtoReflect.Descriptor instead.
func (*RegisterAliasResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_aliases_proto_rawDescGZIP(), []int{1}
}

type GetAliasesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *GetAliasesRequest) Reset() {
	*x = GetAliasesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAliasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasesRequest) ProtoMessage() {}

func (x *GetAliasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasesRequest.ProtoReflect.Descriptor instead.
func (*GetAliasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_aliases_proto_rawDescGZIP(), []int{2}
}

func (x *GetAliasesRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetAliasesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replicas []*Replica `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *GetAliasesResponse) Reset() {
	*x = GetAliasesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAliasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasesResponse) ProtoMessage() {}

func (x *GetAliasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasesResponse.ProtoReflect.Descriptor instead.
func (*GetAliasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_aliases_proto_rawDescGZIP(), []int{3}
}

func (x *GetAliasesResponse) GetReplicas() []*Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type Replica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsdAs    uint64 `protobuf:"varint,1,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	NotAfter uint32 `protobuf:"varint,3,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
}

func (x *Replica) Reset() {
	*x = Replica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replica) ProtoMessage() {}

func (x *Replica) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_aliases_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replica.ProtoReflect.Descriptor instead.
func (*Replica) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_aliases_proto_rawDescGZIP(), []int{4}
}

func (x *Replica) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

func (x *Replica) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Replica) GetNotAfter() uint32 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

var File_proto_control_plane_v1_aliases_proto protoreflect.FileDescriptor

var file_proto_control_plane_v1_aliases_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x67,
	0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x08, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61,
	0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x08, 0x72,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x27, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x51, 0x0a, 0x07,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x64, 0x5f, 0x61,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x73, 0x64, 0x41, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x32,
	0xe7, 0x01, 0x0a, 0x0e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6e, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6c,
	0x69, 0x61, 0x73, 0x12, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x65, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73,
	0x12, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x63, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_control_plane_v1_aliases_proto_rawDescOnce sync.Once
	file_proto_control_plane_v1_aliases_proto_rawDescData = file_proto_control_plane_v1_aliases_proto_rawDesc
)

func file_proto_control_plane_v1_aliases_proto_rawDescGZIP() []byte {
	file_proto_control_plane_v1_aliases_proto_rawDescOnce.Do(func() {
		file_proto_control_plane_v1_aliases_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_control_plane_v1_aliases_proto_rawDescData)
	})
	return file_proto_control_plane_v1_aliases_proto_rawDescData
}

var file_proto_control_plane_v1_aliases_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_control_plane_v1_aliases_proto_goTypes = []interface{}{
	(*RegisterAliasRequest)(nil),  // 0: proto.control_plane.v1.RegisterAliasRequest
	(*RegisterAliasResponse)(nil), // 1: proto.control_plane.v1.RegisterAliasResponse
	(*GetAliasesRequest)(nil),     // 2: proto.control_plane.v1.GetAliasesRequest
	(*GetAliasesResponse)(nil),    // 3: proto.control_plane.v1.GetAliasesResponse
	(*Replica)(nil),               // 4: proto.control_plane.v1.Replica
}
var file_proto_control_plane_v1_aliases_proto_depIdxs = []int32{
	4, // 0: proto.control_plane.v1.RegisterAliasRequest.replicas:type_name -> proto.control_plane.v1.Replica
	4, // 1: proto.control_plane.v1.GetAliasesResponse.replicas:type_name -> proto.control_plane.v1.Replica
	0, // 2: proto.control_plane.v1.AliasesService.RegisterAlias:input_type -> proto.control_plane.v1.RegisterAliasRequest
	2, // 3: proto.control_plane.v1.AliasesService.GetAliases:input_type -> proto.control_plane.v1.GetAliasesRequest
	1, // 4: proto.control_plane.v1.AliasesService.RegisterAlias:output_type -> proto.control_plane.v1.RegisterAliasResponse
	3, // 5: proto.control_plane.v1.AliasesService.GetAliases:output_type -> proto.control_plane.v1.GetAliasesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_control_plane_v1_aliases_proto_init() }
func file_proto_control_plane_v1_aliases_proto_init() {
	if File_proto_control_plane_v1_aliases_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_control_plane_v1_aliases_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterAliasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_v1_aliases_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterAliasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_v1_aliases_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAliasesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_v1_aliases_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAliasesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_v1_aliases_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Replica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_control_plane_v1_aliases_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_plane_v1_aliases_proto_goTypes,
		DependencyIndexes: file_proto_control_plane_v1_aliases_proto_depIdxs,
		MessageInfos:      file_proto_control_plane_v1_aliases_proto_msgTypes,
	}.Build()
	File_proto_control_plane_v1_aliases_proto = out.File
	file_proto_control_plane_v1_aliases_proto_rawDesc = nil
	file_proto_control_plane_v1_aliases_proto_goTypes = nil
	file_proto_control_plane_v1_aliases_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AliasesServiceClient is the client API for AliasesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AliasesServiceClient interface {
	RegisterAlias(ctx context.Context, in *RegisterAliasRequest, opts ...grpc.CallOption) (*RegisterAliasResponse, error)
	GetAliases(ctx context.Context, in *GetAliasesRequest, opts ...grpc.CallOption) (*GetAliasesResponse, error)
}

type aliasesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAliasesServiceClient(cc grpc.ClientConnInterface) AliasesServiceClient {
	return &aliasesServiceClient{cc}
}

func (c *aliasesServiceClient) RegisterAlias(ctx context.Context, in *RegisterAliasRequest, opts ...grpc.CallOption) (*RegisterAliasResponse, error) {
	out := new(RegisterAliasResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.v1.AliasesService/RegisterAlias", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasesServiceClient) GetAliases(ctx context.Context, in *GetAliasesRequest, opts ...grpc.CallOption) (*GetAliasesResponse, error) {
	out := new(GetAliasesResponse)
	err := c.cc.Invoke(ctx, "/proto.control_plane.v1.AliasesService/GetAliases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliasesServiceServer is the server API for AliasesService service.
type AliasesServiceServer interface {
	RegisterAlias(context.Context, *RegisterAliasRequest) (*RegisterAliasResponse, error)
	GetAliases(context.Context, *GetAliasesRequest) (*GetAliasesResponse, error)
}

// UnimplementedAliasesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAliasesServiceServer struct {
}

func (*UnimplementedAliasesServiceServer) RegisterAlias(context.Context, *RegisterAliasRequest) (*RegisterAliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAlias not implemented")
}
func (*UnimplementedAliasesServiceServer) GetAliases(context.Context, *GetAliasesRequest) (*GetAliasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAliases not implemented")
}

func RegisterAliasesServiceServer(s *grpc.Server, srv AliasesServiceServer) {
	s.RegisterService(&_AliasesService_serviceDesc, srv)
}

func _AliasesService_RegisterAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasesServiceServer).RegisterAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.v1.AliasesService/RegisterAlias",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasesServiceServer).RegisterAlias(ctx, req.(*RegisterAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliasesService_GetAliases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAliasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasesServiceServer).GetAliases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.v1.AliasesService/GetAliases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasesServiceServer).GetAliases(ctx, req.(*GetAliasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AliasesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.control_plane.v1.AliasesService",
	HandlerType: (*AliasesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAlias",
			Handler:    _AliasesService_RegisterAlias_Handler,
		},
		{
			MethodName: "GetAliases",
			Handler:    _AliasesService_GetAliases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control_plane/v1/aliases.proto",
}
