// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: proto/control_plane/v1/drkey.proto

package control_plane

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DRKeyLvl1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstIA     uint64               `protobuf:"varint,1,opt,name=dstIA,proto3" json:"dstIA,omitempty"`
	ValTime   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=valTime,proto3" json:"valTime,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *DRKeyLvl1Request) Reset() {
	*x = DRKeyLvl1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyLvl1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyLvl1Request) ProtoMessage() {}

func (x *DRKeyLvl1Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyLvl1Request.ProtoReflect.Descriptor instead.
func (*DRKeyLvl1Request) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_drkey_proto_rawDescGZIP(), []int{0}
}

func (x *DRKeyLvl1Request) GetDstIA() uint64 {
	if x != nil {
		return x.DstIA
	}
	return 0
}

func (x *DRKeyLvl1Request) GetValTime() *timestamp.Timestamp {
	if x != nil {
		return x.ValTime
	}
	return nil
}

func (x *DRKeyLvl1Request) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DRKeyLvl1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstIA      uint64               `protobuf:"varint,1,opt,name=dstIA,proto3" json:"dstIA,omitempty"`
	EpochBegin *timestamp.Timestamp `protobuf:"bytes,2,opt,name=epochBegin,proto3" json:"epochBegin,omitempty"`
	EpochEnd   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=epochEnd,proto3" json:"epochEnd,omitempty"`
	Drkey      []byte               `protobuf:"bytes,4,opt,name=drkey,proto3" json:"drkey,omitempty"`
	Timestamp  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *DRKeyLvl1Response) Reset() {
	*x = DRKeyLvl1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyLvl1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyLvl1Response) ProtoMessage() {}

func (x *DRKeyLvl1Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyLvl1Response.ProtoReflect.Descriptor instead.
func (*DRKeyLvl1Response) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_drkey_proto_rawDescGZIP(), []int{1}
}

func (x *DRKeyLvl1Response) GetDstIA() uint64 {
	if x != nil {
		return x.DstIA
	}
	return 0
}

func (x *DRKeyLvl1Response) GetEpochBegin() *timestamp.Timestamp {
	if x != nil {
		return x.EpochBegin
	}
	return nil
}

func (x *DRKeyLvl1Response) GetEpochEnd() *timestamp.Timestamp {
	if x != nil {
		return x.EpochEnd
	}
	return nil
}

func (x *DRKeyLvl1Response) GetDrkey() []byte {
	if x != nil {
		return x.Drkey
	}
	return nil
}

func (x *DRKeyLvl1Response) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DRKeyLvl2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string                      `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ReqType  uint32                      `protobuf:"varint,2,opt,name=reqType,proto3" json:"reqType,omitempty"`
	ValTime  *timestamp.Timestamp        `protobuf:"bytes,3,opt,name=valTime,proto3" json:"valTime,omitempty"`
	SrcIA    uint64                      `protobuf:"varint,4,opt,name=srcIA,proto3" json:"srcIA,omitempty"`
	DstIA    uint64                      `protobuf:"varint,5,opt,name=dstIA,proto3" json:"dstIA,omitempty"`
	SrcHost  *DRKeyLvl2Request_DRKeyHost `protobuf:"bytes,6,opt,name=srcHost,proto3" json:"srcHost,omitempty"`
	DstHost  *DRKeyLvl2Request_DRKeyHost `protobuf:"bytes,7,opt,name=dstHost,proto3" json:"dstHost,omitempty"`
	Misc     []byte                      `protobuf:"bytes,8,opt,name=misc,proto3" json:"misc,omitempty"`
}

func (x *DRKeyLvl2Request) Reset() {
	*x = DRKeyLvl2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyLvl2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyLvl2Request) ProtoMessage() {}

func (x *DRKeyLvl2Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyLvl2Request.ProtoReflect.Descriptor instead.
func (*DRKeyLvl2Request) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_drkey_proto_rawDescGZIP(), []int{2}
}

func (x *DRKeyLvl2Request) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DRKeyLvl2Request) GetReqType() uint32 {
	if x != nil {
		return x.ReqType
	}
	return 0
}

func (x *DRKeyLvl2Request) GetValTime() *timestamp.Timestamp {
	if x != nil {
		return x.ValTime
	}
	return nil
}

func (x *DRKeyLvl2Request) GetSrcIA() uint64 {
	if x != nil {
		return x.SrcIA
	}
	return 0
}

func (x *DRKeyLvl2Request) GetDstIA() uint64 {
	if x != nil {
		return x.DstIA
	}
	return 0
}

func (x *DRKeyLvl2Request) GetSrcHost() *DRKeyLvl2Request_DRKeyHost {
	if x != nil {
		return x.SrcHost
	}
	return nil
}

func (x *DRKeyLvl2Request) GetDstHost() *DRKeyLvl2Request_DRKeyHost {
	if x != nil {
		return x.DstHost
	}
	return nil
}

func (x *DRKeyLvl2Request) GetMisc() []byte {
	if x != nil {
		return x.Misc
	}
	return nil
}

type DRKeyLvl2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp  *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Drkey      []byte               `protobuf:"bytes,2,opt,name=drkey,proto3" json:"drkey,omitempty"`
	EpochBegin *timestamp.Timestamp `protobuf:"bytes,3,opt,name=epochBegin,proto3" json:"epochBegin,omitempty"`
	EpochEnd   *timestamp.Timestamp `protobuf:"bytes,4,opt,name=epochEnd,proto3" json:"epochEnd,omitempty"`
	Misc       []byte               `protobuf:"bytes,5,opt,name=misc,proto3" json:"misc,omitempty"`
}

func (x *DRKeyLvl2Response) Reset() {
	*x = DRKeyLvl2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyLvl2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyLvl2Response) ProtoMessage() {}

func (x *DRKeyLvl2Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyLvl2Response.ProtoReflect.Descriptor instead.
func (*DRKeyLvl2Response) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_drkey_proto_rawDescGZIP(), []int{3}
}

func (x *DRKeyLvl2Response) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DRKeyLvl2Response) GetDrkey() []byte {
	if x != nil {
		return x.Drkey
	}
	return nil
}

func (x *DRKeyLvl2Response) GetEpochBegin() *timestamp.Timestamp {
	if x != nil {
		return x.EpochBegin
	}
	return nil
}

func (x *DRKeyLvl2Response) GetEpochEnd() *timestamp.Timestamp {
	if x != nil {
		return x.EpochEnd
	}
	return nil
}

func (x *DRKeyLvl2Response) GetMisc() []byte {
	if x != nil {
		return x.Misc
	}
	return nil
}

type DRKeyLvl2Request_DRKeyHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Host []byte `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *DRKeyLvl2Request_DRKeyHost) Reset() {
	*x = DRKeyLvl2Request_DRKeyHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyLvl2Request_DRKeyHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyLvl2Request_DRKeyHost) ProtoMessage() {}

func (x *DRKeyLvl2Request_DRKeyHost) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_v1_drkey_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyLvl2Request_DRKeyHost.ProtoReflect.Descriptor instead.
func (*DRKeyLvl2Request_DRKeyHost) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_v1_drkey_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DRKeyLvl2Request_DRKeyHost) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DRKeyLvl2Request_DRKeyHost) GetHost() []byte {
	if x != nil {
		return x.Host
	}
	return nil
}

var File_proto_control_plane_v1_drkey_proto protoreflect.FileDescriptor

var file_proto_control_plane_v1_drkey_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x72, 0x6b, 0x65, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01,
	0x0a, 0x10, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x73, 0x74, 0x49, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x64, 0x73, 0x74, 0x49, 0x41, 0x12, 0x34, 0x0a, 0x07, 0x76, 0x61, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xed, 0x01, 0x0a, 0x11, 0x44, 0x52, 0x4b,
	0x65, 0x79, 0x4c, 0x76, 0x6c, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x64, 0x73, 0x74, 0x49, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x64,
	0x73, 0x74, 0x49, 0x41, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x42, 0x65, 0x67, 0x69, 0x6e,
	0x12, 0x36, 0x0a, 0x08, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x72, 0x6b, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64, 0x72, 0x6b, 0x65, 0x79, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x8f, 0x03, 0x0a, 0x10, 0x44, 0x52, 0x4b,
	0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x71, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x07, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x72, 0x63,
	0x49, 0x41, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x72, 0x63, 0x49, 0x41, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x73, 0x74, 0x49, 0x41, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x64, 0x73, 0x74, 0x49, 0x41, 0x12, 0x4c, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x48, 0x6f, 0x73, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x07, 0x73, 0x72, 0x63, 0x48,
	0x6f, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x07, 0x64, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x52,
	0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44,
	0x52, 0x4b, 0x65, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x07, 0x64, 0x73, 0x74, 0x48, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x73, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x6d, 0x69, 0x73, 0x63, 0x1a, 0x33, 0x0a, 0x09, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x22, 0xeb, 0x01, 0x0a, 0x11, 0x44,
	0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x72,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64, 0x72, 0x6b, 0x65, 0x79,
	0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x36, 0x0a, 0x08,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x65, 0x70, 0x6f, 0x63,
	0x68, 0x45, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x6d, 0x69, 0x73, 0x63, 0x32, 0x76, 0x0a, 0x10, 0x44, 0x52, 0x4b, 0x65,
	0x79, 0x4c, 0x76, 0x6c, 0x31, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x09,
	0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x31, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x52, 0x4b,
	0x65, 0x79, 0x4c, 0x76, 0x6c, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x32, 0x76, 0x0a, 0x10, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x09, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c,
	0x32, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79,
	0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x63, 0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61,
	0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_control_plane_v1_drkey_proto_rawDescOnce sync.Once
	file_proto_control_plane_v1_drkey_proto_rawDescData = file_proto_control_plane_v1_drkey_proto_rawDesc
)

func file_proto_control_plane_v1_drkey_proto_rawDescGZIP() []byte {
	file_proto_control_plane_v1_drkey_proto_rawDescOnce.Do(func() {
		file_proto_control_plane_v1_drkey_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_control_plane_v1_drkey_proto_rawDescData)
	})
	return file_proto_control_plane_v1_drkey_proto_rawDescData
}

var file_proto_control_plane_v1_drkey_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_control_plane_v1_drkey_proto_goTypes = []interface{}{
	(*DRKeyLvl1Request)(nil),           // 0: proto.control_plane.v1.DRKeyLvl1Request
	(*DRKeyLvl1Response)(nil),          // 1: proto.control_plane.v1.DRKeyLvl1Response
	(*DRKeyLvl2Request)(nil),           // 2: proto.control_plane.v1.DRKeyLvl2Request
	(*DRKeyLvl2Response)(nil),          // 3: proto.control_plane.v1.DRKeyLvl2Response
	(*DRKeyLvl2Request_DRKeyHost)(nil), // 4: proto.control_plane.v1.DRKeyLvl2Request.DRKeyHost
	(*timestamp.Timestamp)(nil),        // 5: google.protobuf.Timestamp
}
var file_proto_control_plane_v1_drkey_proto_depIdxs = []int32{
	5,  // 0: proto.control_plane.v1.DRKeyLvl1Request.valTime:type_name -> google.protobuf.Timestamp
	5,  // 1: proto.control_plane.v1.DRKeyLvl1Request.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 2: proto.control_plane.v1.DRKeyLvl1Response.epochBegin:type_name -> google.protobuf.Timestamp
	5,  // 3: proto.control_plane.v1.DRKeyLvl1Response.epochEnd:type_name -> google.protobuf.Timestamp
	5,  // 4: proto.control_plane.v1.DRKeyLvl1Response.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 5: proto.control_plane.v1.DRKeyLvl2Request.valTime:type_name -> google.protobuf.Timestamp
	4,  // 6: proto.control_plane.v1.DRKeyLvl2Request.srcHost:type_name -> proto.control_plane.v1.DRKeyLvl2Request.DRKeyHost
	4,  // 7: proto.control_plane.v1.DRKeyLvl2Request.dstHost:type_name -> proto.control_plane.v1.DRKeyLvl2Request.DRKeyHost
	5,  // 8: proto.control_plane.v1.DRKeyLvl2Response.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 9: proto.control_plane.v1.DRKeyLvl2Response.epochBegin:type_name -> google.protobuf.Timestamp
	5,  // 10: proto.control_plane.v1.DRKeyLvl2Response.epochEnd:type_name -> google.protobuf.Timestamp
	0,  // 11: proto.control_plane.v1.DRKeyLvl1Service.DRKeyLvl1:input_type -> proto.control_plane.v1.DRKeyLvl1Request
	2,  // 12: proto.control_plane.v1.DRKeyLvl2Service.DRKeyLvl2:input_type -> proto.control_plane.v1.DRKeyLvl2Request
	1,  // 13: proto.control_plane.v1.DRKeyLvl1Service.DRKeyLvl1:output_type -> proto.control_plane.v1.DRKeyLvl1Response
	3,  // 14: proto.control_plane.v1.DRKeyLvl2Service.DRKeyLvl2:output_type -> proto.control_plane.v1.DRKeyLvl2Response
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_control_plane_v1_drkey_proto_init() }
func file_proto_control_plane_v1_drkey_proto_init() {
	if File_proto_control_plane_v1_drkey_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_control_plane_v1_drkey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyLvl1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_v1_drkey_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyLvl1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_v1_drkey_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyLvl2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_v1_drkey_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyLvl2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_control_plane_v1_drkey_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyLvl2Request_DRKeyHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_control_plane_v1_drkey_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_control_plane_v1_drkey_proto_goTypes,
		DependencyIndexes: file_proto_control_plane_v1_drkey_proto_depIdxs,
		MessageInfos:      file_proto_control_plane_v1_drkey_proto_msgTypes,
	}.Build()
	File_proto_control_plane_v1_drkey_proto = out.File
	file_proto_control_plane_v1_drkey_proto_rawDesc = nil
	file_proto_control_plane_v1_drkey_proto_goTypes = nil
	file_proto_control_plane_v1_drkey_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DRKeyLvl1ServiceClient is the client API for DRKeyLvl1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DRKeyLvl1ServiceClient interface {
	DRKeyLvl1(ctx context.Context, in *DRKeyLvl1Request, opts ...grpc.CallOption) (*DRKeyLvl1Response, error)
}

type dRKeyLvl1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDRKeyLvl1ServiceClient(cc grpc.ClientConnInterface) DRKeyLvl1ServiceClient {
	return &dRKeyLvl1ServiceClient{cc}
}

func (c *dRKeyLvl1ServiceClient) DRKeyLvl1(ctx context.Context, in *DRKeyLvl1Request, opts ...grpc.CallOption) (*DRKeyLvl1Response, error) {
	out := new(DRKeyLvl1Response)
	err := c.cc.Invoke(ctx, "/proto.control_plane.v1.DRKeyLvl1Service/DRKeyLvl1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DRKeyLvl1ServiceServer is the server API for DRKeyLvl1Service service.
type DRKeyLvl1ServiceServer interface {
	DRKeyLvl1(context.Context, *DRKeyLvl1Request) (*DRKeyLvl1Response, error)
}

// UnimplementedDRKeyLvl1ServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDRKeyLvl1ServiceServer struct {
}

func (*UnimplementedDRKeyLvl1ServiceServer) DRKeyLvl1(context.Context, *DRKeyLvl1Request) (*DRKeyLvl1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DRKeyLvl1 not implemented")
}

func RegisterDRKeyLvl1ServiceServer(s *grpc.Server, srv DRKeyLvl1ServiceServer) {
	s.RegisterService(&_DRKeyLvl1Service_serviceDesc, srv)
}

func _DRKeyLvl1Service_DRKeyLvl1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DRKeyLvl1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRKeyLvl1ServiceServer).DRKeyLvl1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.v1.DRKeyLvl1Service/DRKeyLvl1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRKeyLvl1ServiceServer).DRKeyLvl1(ctx, req.(*DRKeyLvl1Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _DRKeyLvl1Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.control_plane.v1.DRKeyLvl1Service",
	HandlerType: (*DRKeyLvl1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DRKeyLvl1",
			Handler:    _DRKeyLvl1Service_DRKeyLvl1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control_plane/v1/drkey.proto",
}

// DRKeyLvl2ServiceClient is the client API for DRKeyLvl2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DRKeyLvl2ServiceClient interface {
	DRKeyLvl2(ctx context.Context, in *DRKeyLvl2Request, opts ...grpc.CallOption) (*DRKeyLvl2Response, error)
}

type dRKeyLvl2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDRKeyLvl2ServiceClient(cc grpc.ClientConnInterface) DRKeyLvl2ServiceClient {
	return &dRKeyLvl2ServiceClient{cc}
}

func (c *dRKeyLvl2ServiceClient) DRKeyLvl2(ctx context.Context, in *DRKeyLvl2Request, opts ...grpc.CallOption) (*DRKeyLvl2Response, error) {
	out := new(DRKeyLvl2Response)
	err := c.cc.Invoke(ctx, "/proto.control_plane.v1.DRKeyLvl2Service/DRKeyLvl2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DRKeyLvl2ServiceServer is the server API for DRKeyLvl2Service service.
type DRKeyLvl2ServiceServer interface {
	DRKeyLvl2(context.Context, *DRKeyLvl2Request) (*DRKeyLvl2Response, error)
}

// UnimplementedDRKeyLvl2ServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDRKeyLvl2ServiceServer struct {
}

func (*UnimplementedDRKeyLvl2ServiceServer) DRKeyLvl2(context.Context, *DRKeyLvl2Request) (*DRKeyLvl2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DRKeyLvl2 not implemented")
}

func RegisterDRKeyLvl2ServiceServer(s *grpc.Server, srv DRKeyLvl2ServiceServer) {
	s.RegisterService(&_DRKeyLvl2Service_serviceDesc, srv)
}

func _DRKeyLvl2Service_DRKeyLvl2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DRKeyLvl2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRKeyLvl2ServiceServer).DRKeyLvl2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.control_plane.v1.DRKeyLvl2Service/DRKeyLvl2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRKeyLvl2ServiceServer).DRKeyLvl2(ctx, req.(*DRKeyLvl2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _DRKeyLvl2Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.control_plane.v1.DRKeyLvl2Service",
	HandlerType: (*DRKeyLvl2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DRKeyLvl2",
			Handler:    _DRKeyLvl2Service_DRKeyLvl2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control_plane/v1/drkey.proto",
}
