// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/cs/reservationstorage (interfaces: Store)

// Package mock_reservationstorage is a generated GoMock package.
package mock_reservationstorage

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reservation "github.com/scionproto/scion/go/cs/reservation"
	e2e "github.com/scionproto/scion/go/cs/reservation/e2e"
	segment "github.com/scionproto/scion/go/cs/reservation/segment"
	addr "github.com/scionproto/scion/go/lib/addr"
	reflect "reflect"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AdmitE2EReservation mocks base method
func (m *MockStore) AdmitE2EReservation(arg0 context.Context, arg1 e2e.SetupRequest) (reservation.MessageWithPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdmitE2EReservation", arg0, arg1)
	ret0, _ := ret[0].(reservation.MessageWithPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdmitE2EReservation indicates an expected call of AdmitE2EReservation
func (mr *MockStoreMockRecorder) AdmitE2EReservation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdmitE2EReservation", reflect.TypeOf((*MockStore)(nil).AdmitE2EReservation), arg0, arg1)
}

// AdmitSegmentReservation mocks base method
func (m *MockStore) AdmitSegmentReservation(arg0 context.Context, arg1 *segment.SetupReq) (reservation.MessageWithPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdmitSegmentReservation", arg0, arg1)
	ret0, _ := ret[0].(reservation.MessageWithPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdmitSegmentReservation indicates an expected call of AdmitSegmentReservation
func (mr *MockStoreMockRecorder) AdmitSegmentReservation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdmitSegmentReservation", reflect.TypeOf((*MockStore)(nil).AdmitSegmentReservation), arg0, arg1)
}

// CleanupE2EReservation mocks base method
func (m *MockStore) CleanupE2EReservation(arg0 context.Context, arg1 *e2e.CleanupReq) (reservation.MessageWithPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupE2EReservation", arg0, arg1)
	ret0, _ := ret[0].(reservation.MessageWithPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupE2EReservation indicates an expected call of CleanupE2EReservation
func (mr *MockStoreMockRecorder) CleanupE2EReservation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupE2EReservation", reflect.TypeOf((*MockStore)(nil).CleanupE2EReservation), arg0, arg1)
}

// CleanupSegmentReservation mocks base method
func (m *MockStore) CleanupSegmentReservation(arg0 context.Context, arg1 *segment.CleanupReq) (reservation.MessageWithPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupSegmentReservation", arg0, arg1)
	ret0, _ := ret[0].(reservation.MessageWithPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupSegmentReservation indicates an expected call of CleanupSegmentReservation
func (mr *MockStoreMockRecorder) CleanupSegmentReservation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupSegmentReservation", reflect.TypeOf((*MockStore)(nil).CleanupSegmentReservation), arg0, arg1)
}

// ConfirmSegmentReservation mocks base method
func (m *MockStore) ConfirmSegmentReservation(arg0 context.Context, arg1 *segment.IndexConfirmationReq) (reservation.MessageWithPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmSegmentReservation", arg0, arg1)
	ret0, _ := ret[0].(reservation.MessageWithPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmSegmentReservation indicates an expected call of ConfirmSegmentReservation
func (mr *MockStoreMockRecorder) ConfirmSegmentReservation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmSegmentReservation", reflect.TypeOf((*MockStore)(nil).ConfirmSegmentReservation), arg0, arg1)
}

// DeleteExpiredIndices mocks base method
func (m *MockStore) DeleteExpiredIndices(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredIndices", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredIndices indicates an expected call of DeleteExpiredIndices
func (mr *MockStoreMockRecorder) DeleteExpiredIndices(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredIndices", reflect.TypeOf((*MockStore)(nil).DeleteExpiredIndices), arg0)
}

// GetSegmentRsvsFromSrcDstIA mocks base method
func (m *MockStore) GetSegmentRsvsFromSrcDstIA(arg0 context.Context, arg1, arg2 addr.IA) ([]*segment.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegmentRsvsFromSrcDstIA", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*segment.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegmentRsvsFromSrcDstIA indicates an expected call of GetSegmentRsvsFromSrcDstIA
func (mr *MockStoreMockRecorder) GetSegmentRsvsFromSrcDstIA(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegmentRsvsFromSrcDstIA", reflect.TypeOf((*MockStore)(nil).GetSegmentRsvsFromSrcDstIA), arg0, arg1, arg2)
}

// InitSegmentReservation mocks base method
func (m *MockStore) InitSegmentReservation(arg0 context.Context, arg1 *segment.SetupReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitSegmentReservation", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitSegmentReservation indicates an expected call of InitSegmentReservation
func (mr *MockStoreMockRecorder) InitSegmentReservation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitSegmentReservation", reflect.TypeOf((*MockStore)(nil).InitSegmentReservation), arg0, arg1)
}

// TearDownSegmentReservation mocks base method
func (m *MockStore) TearDownSegmentReservation(arg0 context.Context, arg1 *segment.TeardownReq) (reservation.MessageWithPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TearDownSegmentReservation", arg0, arg1)
	ret0, _ := ret[0].(reservation.MessageWithPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TearDownSegmentReservation indicates an expected call of TearDownSegmentReservation
func (mr *MockStoreMockRecorder) TearDownSegmentReservation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TearDownSegmentReservation", reflect.TypeOf((*MockStore)(nil).TearDownSegmentReservation), arg0, arg1)
}
