// Copyright 2021 ETH Zurich
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

option go_package = "github.com/scionproto/scion/go/pkg/proto/colibri";

package proto.colibri.v1;

import "google/protobuf/timestamp.proto";

service Colibri {
    rpc TestPeer(TestingMessage) returns (TestingMessage) {}
    rpc SetupSegment(SegmentSetupRequest) returns (SegmentSetupResponse) {}
    rpc ConfirmSegmentIndex(Request) returns (Response) {}
    rpc ActivateSegmentIndex(Request) returns (Response) {}
    rpc TeardownSegment(Request) returns (Response) {}
    rpc CleanupSegmentIndex(Request) returns (Response) {}

    rpc ListReservations(ListRequest) returns (ListResponse) {}
    rpc SetupE2e(E2eSetupRequest) returns (E2eSetupResponse) {}
    rpc CleanupE2eIndex(Request) returns (Response) {}
}

message TestingMessage{
    string message = 1;
    google.protobuf.Timestamp timestamp = 2;
    bytes data = 3;
}

// /////////////////////////////////////////////////

message ReservationID {
    uint64 asid = 1;
    bytes suffix = 2;
}

message IndexState {
    enum State {
        PENDING = 0;
        ACTIVE = 1;
    }
    State state = 1;
}

message PathEndProps {
    bool local = 1;
    bool transfer = 2;
}

message AllocationBead {
    uint32 allocbw = 1;
    uint32 maxbw = 2;
}

message PathStep {
    uint64 ia = 1;
    uint32 ingress = 2;
    uint32 egress =3;
}

message TransparentPath {
    uint32 current_step = 1;
    repeated PathStep steps = 2;
    uint32 spathType = 3;
    bytes spathRaw = 4;
}

////////////////////////////////////////

message Request {
    ReservationID id = 1;
    uint32 index = 2;
    uint32 timestamp = 3;
    TransparentPath path = 4;
}

message Response {
    message Success {}
    message Failure {
        uint32 error_code = 1;
        string message = 2;
        uint32 failing_hop = 3;
    }

    oneof success_failure {
        Success success = 1;
        Failure failure = 2;
    }
}

message SegmentSetupRequest {
    message Params {
        uint32 expiration_time = 1;
        uint32 rlc = 2;
        uint32 path_type = 3;
        uint32 minbw = 4;
        uint32 maxbw = 5;
        uint32 splitcls = 6;
        PathEndProps props_at_start = 7;
        PathEndProps props_at_end = 8;
        repeated AllocationBead allocationtrail = 9;
        bool reverse_traveling = 10;
    }

    Request base = 1;
    Params params = 2;
    // when a down rsv., indicates the req. is just traveling to the last AS to be
    // re-requested from there (admission is done in the direction of the reservation).
}

message SegmentSetupResponse {
    message Failure {
        Response.Failure failure = 1;
        SegmentSetupRequest.Params request = 2;
    }

    oneof success_failure {
        bytes token = 1;
        Failure failure = 2;
    }
}

message ListRequest {
    uint64 dst_ia = 1;
}

message ListResponse {
    message Reservations {
        message ReservationLooks {
            ReservationID ID = 1;
            uint64 dst_ia = 2;
            // other properties?
        }
        repeated ReservationLooks reservations = 1;
    }

    oneof success_failure {
        Reservations reservations = 1;
        string failure_message = 2;
    }
}

message E2eSetupRequest {
    message PathParams {
        ReservationID up = 1;
        ReservationID core = 2;
        ReservationID down = 3;
        uint32 current_segment = 4; // index of the current segment.
                                    // If the node is transfer, the first segment it belongs to.
    }
    message E2eSetupBead {
        uint32 maxbw = 1;
        bytes hopfield = 2;
    }
    message Failure {
        uint32 failed_step = 1;
        string Message = 2;
    }

    Request base = 1; // the path here is from src to dst
    uint32 requestedBw = 2;
    PathParams params = 3;
    repeated E2eSetupBead allocationtrail = 4; // even failed nodes will write an entry
    Failure failure = 5; // if present: info about the failure
}

message E2eSetupResponse {
}
