// Copyright 2021 ETH Zurich
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

option go_package = "github.com/scionproto/scion/go/pkg/proto/colibri";

package proto.colibri.v1;

import "google/protobuf/timestamp.proto";

service Colibri {
    rpc TestPeer(TestingMessage) returns (TestingMessage) {}
    rpc SetupSegment(SegmentSetupRequest) returns (SegmentSetupResponse) {}
    rpc ConfirmSegmentIndex(Request) returns (Response) {}
    rpc ActivateSegmentIndex(Request) returns (Response) {}
    rpc TeardownSegment(Request) returns (Response) {}
    rpc CleanupSegmentIndex(Request) returns (Response) {}

}

message TestingMessage{
    string message = 1;
    google.protobuf.Timestamp timestamp = 2;
    bytes data = 3;
}

// /////////////////////////////////////////////////

message ReservationID {
    uint64 asid = 1;
    bytes suffix = 2;
}

message IndexState {
    enum State {
        PENDING = 0;
        ACTIVE = 1;
    }
    State state = 1;
}

message PathEndProps {
    bool local = 1;
    bool transfer = 2;
}

message AllocationBead {
    uint32 allocbw = 1;
    uint32 maxbw = 2;
}

message PathStep { // without IA
    uint32 ingress = 1;
    uint32 egress =2;
}

message OpaquePath {
    uint32 current_step = 1;
    repeated PathStep steps = 2;
    uint32 spathType = 3;
    bytes spathRaw = 4;
}

////////////////////////////////////////

message Request {
    ReservationID id = 1;
    uint32 index = 2;
    uint32 timestamp = 3;
    OpaquePath opaque = 4;
}


message SegmentSetupRequest {
    Request base = 1;
    message Params {
        uint32 expiration_time = 1;
        uint32 rlc = 2;
        uint32 path_type = 3;
        uint32 minbw = 4;
        uint32 maxbw = 5;
        uint32 splitcls = 6;
        PathEndProps props_at_start = 7;
        PathEndProps props_at_end = 8;
        repeated AllocationBead allocationtrail = 9;
    }
    Params params = 2;
}

message SegmentSetupResponse {
    message Failure {
        Response.Failure failure = 1;
        SegmentSetupRequest.Params request = 2;
    }
    oneof success_failure {
        bytes token = 1;
        Failure failure = 2;
    }
}

message Response {
    message Success {}
    message Failure {
        uint32 error_code = 1;
        string message = 2;
        uint32 failing_hop = 3;
    }
    oneof success_failure {
        Success success = 1;
        Failure failure = 2;
    }
}
