// Copyright 2026 ETH Zurich
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestResolveGOROOTPrefersRuntime(t *testing.T) {
	goroot, err := resolveGOROOT(func() (string, error) {
		t.Fatal("go env fallback should not be called when runtime.GOROOT is set")
		return "", nil
	})
	if err != nil {
		t.Fatalf("resolve GOROOT: %v", err)
	}
	if goroot == "" {
		t.Fatal("expected non-empty GOROOT")
	}
}

func TestNormalizeNewlines(t *testing.T) {
	got := string(normalizeNewlines([]byte("a\r\nb\rc\n")))
	want := "a\nb\nc\n"
	if got != want {
		t.Fatalf("normalizeNewlines = %q, want %q", got, want)
	}
}

func TestBuildOutputAddsHeaderAndNormalizesBody(t *testing.T) {
	dir := t.TempDir()
	srcPath := filepath.Join(dir, "aes_amd64.s")
	if err := os.WriteFile(srcPath, []byte("// body\r\nTEXT foo\r\n"), 0o644); err != nil {
		t.Fatalf("write source: %v", err)
	}

	got, err := buildOutput(srcPath, filepath.Join("src", "crypto", "internal", "fips140", "aes", "aes_amd64.s"), "go-test")
	if err != nil {
		t.Fatalf("buildOutput: %v", err)
	}

	want := "// Code generated by gen_hbird_aesasm. DO NOT EDIT.\n" +
		"// Source: src/crypto/internal/fips140/aes/aes_amd64.s\n" +
		"// Go version: go-test\n\n" +
		"// body\nTEXT foo\n"
	if string(got) != want {
		t.Fatalf("buildOutput mismatch:\n got: %q\nwant: %q", string(got), want)
	}
}

func TestWriteIfChanged(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.s")
	content := []byte("same\n")

	if err := writeIfChanged(path, content); err != nil {
		t.Fatalf("first write: %v", err)
	}
	info1, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat after first write: %v", err)
	}

	if err := writeIfChanged(path, content); err != nil {
		t.Fatalf("second write: %v", err)
	}
	info2, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat after second write: %v", err)
	}
	if !info1.ModTime().Equal(info2.ModTime()) {
		t.Fatalf("expected unchanged file to keep modtime, got %v then %v", info1.ModTime(), info2.ModTime())
	}
}

func TestCheckFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.s")
	content := []byte("line1\r\nline2\r\n")
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}

	if err := checkFile(path, []byte("line1\nline2\n")); err != nil {
		t.Fatalf("checkFile: %v", err)
	}
}
