// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/cs/reservationstore (interfaces: Manager)

// Package mock_reservationstore is a generated GoMock package.
package mock_reservationstore

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	segment "github.com/scionproto/scion/go/cs/reservation/segment"
	reservationstorage "github.com/scionproto/scion/go/cs/reservationstorage"
	addr "github.com/scionproto/scion/go/lib/addr"
	snet "github.com/scionproto/scion/go/lib/snet"
	reflect "reflect"
	time "time"
)

// MockManager is a mock of Manager interface
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// LocalIA mocks base method
func (m *MockManager) LocalIA() addr.IA {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalIA")
	ret0, _ := ret[0].(addr.IA)
	return ret0
}

// LocalIA indicates an expected call of LocalIA
func (mr *MockManagerMockRecorder) LocalIA() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalIA", reflect.TypeOf((*MockManager)(nil).LocalIA))
}

// Name mocks base method
func (m *MockManager) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (mr *MockManagerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockManager)(nil).Name))
}

// Now mocks base method
func (m *MockManager) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now
func (mr *MockManagerMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockManager)(nil).Now))
}

// PathsTo mocks base method
func (m *MockManager) PathsTo(arg0 context.Context, arg1 addr.IA) ([]snet.Path, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathsTo", arg0, arg1)
	ret0, _ := ret[0].([]snet.Path)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathsTo indicates an expected call of PathsTo
func (mr *MockManagerMockRecorder) PathsTo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathsTo", reflect.TypeOf((*MockManager)(nil).PathsTo), arg0, arg1)
}

// Request mocks base method
func (m *MockManager) Request(arg0 context.Context, arg1 *segment.SetupReq) (*segment.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", arg0, arg1)
	ret0, _ := ret[0].(*segment.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request
func (mr *MockManagerMockRecorder) Request(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockManager)(nil).Request), arg0, arg1)
}

// RequestMany mocks base method
func (m *MockManager) RequestMany(arg0 context.Context, arg1 []*segment.SetupReq) ([]*segment.Reservation, []error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestMany", arg0, arg1)
	ret0, _ := ret[0].([]*segment.Reservation)
	ret1, _ := ret[1].([]error)
	return ret0, ret1
}

// RequestMany indicates an expected call of RequestMany
func (mr *MockManagerMockRecorder) RequestMany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestMany", reflect.TypeOf((*MockManager)(nil).RequestMany), arg0, arg1)
}

// Run mocks base method
func (m *MockManager) Run(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", arg0)
}

// Run indicates an expected call of Run
func (mr *MockManagerMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockManager)(nil).Run), arg0)
}

// Store mocks base method
func (m *MockManager) Store() reservationstorage.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store")
	ret0, _ := ret[0].(reservationstorage.Store)
	return ret0
}

// Store indicates an expected call of Store
func (mr *MockManagerMockRecorder) Store() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockManager)(nil).Store))
}
